# -*- coding: utf-8 -*-
"""16_Bonus. Lux

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bq2SuH1II7OY4LPrXBdleiO6XVOHZugE

# **BONUS**

# **Lux**
"""

# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# %matplotlib inline

pip install lux-api

"""##Jupyter Notebook ishlatuvhcilar:
##uchun
"""

# jupyter nbextension install --py luxwidget
# jupyter nbextension enable --py luxwidget

"""## Google Colap ishlatuvchilari
## uchun
"""

from google.colab import output
output.enable_custom_widget_manager()

import lux
import pandas as pd
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/merc.csv")
df=df[df.year>=2010] # 2010-yildan keyin chiqqan mashinalarni saqlab qolamiz
df=df[df.transmission!='Other'] # Faqat avtomat, mexanik va yarim-avtomat mashinalarni olib qolamiz
df=df[df.fuelType!='Other'] # Faqat benzin, dizel va gibrid mashinalarni olib qolamiz
df['year'] = pd.to_datetime(df['year'], format='%Y')
df.head()

"""#Har hil turdagi grafiklarini ko'rishimiz mumkin
# Toggle pandas/Lux tugmasini bosish orqali.
"""

df.intent = ["price","mileage"]
df

"""###Lux — bu interaktiv va tavsiyaviy ma'lumotlar tahlili kutubxonasi bo'lib, u Pandas DataFramelaringizga bevosita integratsiya qilinadi. Uning asosiy maqsadi — ma'lumotlarni tahlil qilish va vizualizatsiya qilish jarayonini avtomatlashtirish va tezlashtirishdir. Oddiygina qilib aytganda, Lux sizga DataFramening mazmuniga qarab, avtomatik ravishda turli xil grafik va vizualizatsiyalarni taklif qiladi va ularni ko'rsatadi. Bu ma'lumotlardagi naqshlar, korrelyatsiyalar va anomaliyalarni topishga yordam beradi, hatto siz qaysi vizualizatsiyani ishlatishni bilmasangiz ham. U ma'lumotlarni o'rganish (EDA - Exploratory Data Analysis) jarayonini sezilarli darajada soddalashtiradi.

# **NEW SECTION**

### Lux mavjud Pandas kodini o'zgartirmasdan ishlatilishi mumkin. Bu yerda biz kollejlar va ularning xususiyatlari ma'lumotlar to'plamini yuklash uchun Pandasning read_csv buyrug'idan foydalanamiz.
"""

df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/college.csv")
df

"""##Yuqoridagi yani jadval ustidagi Toggle Pandas/Lux tugmasini bosgandan keyin grafiklarni chiqarib beradi"""

df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/college.csv")
df

"""### Tadqiqotning har bir bosqichida ma'lumotlar ramkasi vizualizatsiyasidan tashqari, siz Luxga sizni qiziqtirgan atributlar va qiymatlarni belgilashingiz mumkin. Ushbu maqsadga asoslanib, Lux foydalanuvchilarni tadqiqotdagi keyingi bosqichlarga yo'naltiradi.

### AverageCostMasalan, bizni va atributlari qiziqtirishi mumkin SATAverage
"""

df.intent = ["AverageCost","SATAverage"]
df

"""### Vidjetning chap tomonida joriy vizualizatsiya, ya'ni foydalanuvchi qiziqqan narsalar asosida yaratilgan joriy vizualizatsiya ko'rsatilgan. O'ng tomonda Lux vidjetda alohida yorliqlar sifatida tashkil etilgan uchta tavsiyalar to'plamini yaratadi:

### EnhanceAverageCostjoriy tanlovga qo'shimcha atribut qo'shadi, asosan qo'shimcha o'zgaruvchilar va munosabatlariga qanday ta'sir qilishini ta'kidlaydi SATAverage. Agar biz munosabatni ga bo'lsak, davlat kollejlari (qizil rangda ko'rsatilgan) va xususiy kollejlar (ko'k rangda) o'rtasida aniq farq borligini ko'ramiz

### Aytaylik , AverageCost dan tashqari, siz Expenditure yoki MedianDebt kabi turli moliyaviy ko'rsatkichlar bilan bog'liq atributlar ro'yxatini va ularning FundingModel ga nisbatan qanday taqsimlanishini ko'rib chiqishga qiziqasiz .

### Siz atributlar ro'yxati orasidagi YOKI munosabatini ko'rsatuvchi | belgisi bilan ajratilgan kerakli atributlar ro'yxatini belgilashingiz mumkin . Agar bir nechta bandlar ko'rsatilgan bo'lsa, Lux avtomatik ravishda ko'rsatilgan atributlarning kombinatsiyalarini yaratadi.
"""

possible_attributes = "AverageCost|Expenditure|MedianDebt|MedianEarnings"
df.intent = [possible_attributes,"FundingModel"]
df

"""# **NEW SECTION**"""

from lux.vis.Vis import Vis
Vis(["Region=New England","MedianEarnings"],df)

"""## Vizualizatsiya to'plamlari bilan ishlash uchun kuchli til:
### Lux qisman belgilangan so'rovlarga asoslangan vizualizatsiya to'plamlari bilan ishlash uchun kuchli abstraksiyani taqdim etadi. Foydalanuvchilar filtr yoki atribut qiymatlari kombinatsiyalari ustidan takrorlanish va ko'p sonli vizualizatsiyalarni tezda ko'rib chiqish uchun ro'yxat yoki joker belgini taqdim etishlari mumkin. Qisman spetsifikatsiya ZQL va CompassQL kabi vizualizatsiya so'rov tillari bo'yicha mavjud ishlardan ilhomlangan .

### AverageCostMasalan, biz taqsimotning turli s da qanday farq qilishi bilan qiziqamiz Region.
"""

from lux.vis.VisList import VisList
VisList(["Region=?","AverageCost"],df)